### ISSUE TITLE
Réparer la carte des membres

### ISSUE THREAD

**Issue by gawel** [AFPy/site-web#2]
Il faudrait recoder le machin. Y a plus de theme, y a trop de membres et ça marche plus.

http://www.afpy.org/membres/carte

**Comment by richardbarran** [comment]
En date d'aujourd'hui (Octobre 2015) la carte ne fonctionne plus du tout - on a une carte de France, mais zero membres :-)

**Comment by gawel** [comment]
Je crois qu'on peut dire qu'elle est morte à jamais
